// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQiJ13C3Wcske6hf0B_NM9vlt6KJyn6_0',
    appId: '1:796992721580:web:11459f33435e5c9384c509',
    messagingSenderId: '796992721580',
    projectId: 'stravaproject-402809',
    authDomain: 'stravaproject-402809.firebaseapp.com',
    storageBucket: 'stravaproject-402809.appspot.com',
    measurementId: 'G-8488H968SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi6bmxcYTloTfLNAjkaSokmlkhB2DxSXw',
    appId: '1:796992721580:android:fbba8c7839be2b8684c509',
    messagingSenderId: '796992721580',
    projectId: 'stravaproject-402809',
    storageBucket: 'stravaproject-402809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-rdz2UExu9zSoCDSJGoVdFWNkppvtldc',
    appId: '1:796992721580:ios:9578145d0efbe1b184c509',
    messagingSenderId: '796992721580',
    projectId: 'stravaproject-402809',
    storageBucket: 'stravaproject-402809.appspot.com',
    iosBundleId: 'com.example.stravaclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-rdz2UExu9zSoCDSJGoVdFWNkppvtldc',
    appId: '1:796992721580:ios:3564d0f43a07afdf84c509',
    messagingSenderId: '796992721580',
    projectId: 'stravaproject-402809',
    storageBucket: 'stravaproject-402809.appspot.com',
    iosBundleId: 'com.example.stravaclone.RunnerTests',
  );
}
